keys:
  - &jsteward EEE87C527B2D913A8CBAD48C725079137D8A5B65
  - &minato 9491a58334d9aa0d35f02b532a88523d1e5812ba
  - &kage d28319a43aaf6d8ec8817126ad3951f005b24533
  - &shigeru 7f7b670838a10ddf6645f61ecb870ff13b0b3844
  - &nagisa 72879b604d86f86d89833ab15a668f432cde37e6
  - &iori 1c66b66a62109f653fcb8f63fcd3d7fab9a53fb6
creation_rules:
  - path_regex: nixos/minato/secrets\.yaml$
    key_groups:
      - pgp:
        - *jsteward
        - *minato
  - path_regex: nixos/kage/secrets\.yaml$
    key_groups:
      - pgp:
        - *jsteward
        - *kage
  - path_regex: nixos/shigeru/secrets\.yaml$
    key_groups:
      - pgp:
        - *jsteward
        - *shigeru
  - path_regex: nixos/nagisa/secrets\.yaml$
    key_groups:
      - pgp:
        - *jsteward
        - *nagisa
  - path_regex: nixos/iori/secrets\.yaml$
    key_groups:
      - pgp:
        - *jsteward
        - *iori
