# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  ariang = {
    pname = "ariang";
    version = "0d4eb2d15ea71c76aff07236c2560984fb3ec690";
    src = fetchgit {
      url = "https://github.com/KireinaHoro/AriaNg";
      rev = "0d4eb2d15ea71c76aff07236c2560984fb3ec690";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "17lmw2jj77569qqfiz0d34a8ln2di0i4vqinxswhvnsfcqzc8h3j";
    };
    
  };
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "98314a132c58e17c77d76a992465e55c89f73b0b";
    src = fetchgit {
      url = "https://github.com/felixonmars/dnsmasq-china-list";
      rev = "98314a132c58e17c77d76a992465e55c89f73b0b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1g96mgaciyzqjsqzj3hvb2f9ldlargi1jjp5dad7glqay1i553nh";
    };
    
  };
  hosts-blocklists = {
    pname = "hosts-blocklists";
    version = "6e098dce9225681827520a0956c707ec59115e75";
    src = fetchgit {
      url = "https://github.com/notracking/hosts-blocklists";
      rev = "6e098dce9225681827520a0956c707ec59115e75";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0jv0df9vavjl75yd13rpg16gw9g2zqcvkjwhq5202y7ga4qssglx";
    };
    
  };
  rait = {
    pname = "rait";
    version = "e84e803641ec3a2dce5670275ea8d5497608f483";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "e84e803641ec3a2dce5670275ea8d5497608f483";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "18fs50kr8nmkhhb58i8wzki5rnx6qny207g07a2836z8gac4z95x";
    };
    
  };
}
