[rait]
src.git = "https://gitlab.com/NickCao/RAIT"
fetch.git = "https://gitlab.com/NickCao/RAIT"

[dnsmasq-china-list]
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.git = "https://github.com/felixonmars/dnsmasq-china-list"

[hosts-blocklists]
src.git = "https://github.com/notracking/hosts-blocklists"
fetch.git = "https://github.com/notracking/hosts-blocklists"
