name: image-cache
description: fetch/update cached one docker image
inputs:
  image-name:
    required: true
  cache-dir:
    default: /image-cache
  tar-name:
    default: image.tar
runs:
  using: composite
  steps:
    - name: create image cache dir and mount tmpfs
      shell: bash
      run: |
        sudo mkdir -p ${{inputs.cache-dir}}
        sudo mount -t tmpfs tmpfs ${{inputs.cache-dir}}
        sudo chown $(id -u):$(id -g) ${{inputs.cache-dir}}
    - id: image-cache
      name: try load image from cache
      uses: actions/cache@v4
      with:
        path: ${{inputs.cache-dir}}
        key: ${{runner.os}}-image-cache
    - if: steps.image-cache.outputs.cache-hit != 'true'
      name: cache miss; pull image
      shell: bash
      run: docker pull ${{inputs.image-name}}
    - if: steps.image-cache.outputs.cache-hit != 'true'
      name: cache miss; store image in cache in post
      uses: webiny/action-post-run@3.1.0
      with:
        run: docker save -o ${{inputs.cache-dir}}/${{inputs.tar-name}} ${{inputs.image-name}}
    - if: steps.image-cache.outputs.cache-hit == 'true'
      name: cache hit; restore image and delete tar archive
      shell: bash
      run: |
        docker load -i ${{inputs.cache-dir}}/${{inputs.tar-name}}
        rm ${{inputs.cache-dir}}/${{inputs.tar-name}}
