name: 'Deploy flake with deploy-rs'
inputs:
  flake:
    description: 'Flake to deploy'
    required: true
  privkey:
    description: 'Private key for deploying'
    required: true
  host:
    description: 'Host to deploy'
    required: true
runs:
  using: 'docker'
  image: 'docker://kireinahoro/flakes-ci:v1'
  args:
    - ${{ inputs.flake }}
    - ${{ inputs.privkey }}
    - ${{ inputs.host }}
