name: 'Deploy flake with deploy-rs'
inputs:
  flake:
    description: 'Flake to deploy'
    required: true
  privkey:
    description: 'Private key for deploying'
    required: true
  host:
    description: 'Host to deploy'
    required: true
runs:
  using: 'docker'
  image: 'docker://kireinahoro/flakes-base:v1'
  args:
    - >-
      echo "${{inputs.privkey}}" > privkey &&
      chmod 400 privkey &&
      nix run ${{inputs.flake}}#deploy-rs.deploy-rs --
        --ssh-opts ="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i privkey"
        ${{inputs.flake}}#${{inputs.host}}
