name: 'Bump flake input lock'
inputs:
  input:
    description: 'Name of input to bump'
    required: true
runs:
  using: 'docker'
  image: 'docker://kireinahoro/flakes-base:v1'
  args:
    - nix flake lock --update-input ${{inputs.input}}
