# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "6e662c2b92ca071bafd15b38d615f859437b1520";
    src = fetchgit {
      url = "https://github.com/felixonmars/dnsmasq-china-list";
      rev = "6e662c2b92ca071bafd15b38d615f859437b1520";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-zwTW3Z9x179/kfxVLHpnQRCIsj4TU+djjE06eimDXCU=";
    };
    date = "2024-01-17";
  };
  hosts-blocklists = {
    pname = "hosts-blocklists";
    version = "2ab426e806985d0d3d1c3eb447d7e772a836e10d";
    src = fetchgit {
      url = "https://github.com/notracking/hosts-blocklists";
      rev = "2ab426e806985d0d3d1c3eb447d7e772a836e10d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-nKNz9ux1FPxoL14VZtH/1tfnn67LeXmdVQJz7I9+Srk=";
    };
    date = "2023-06-26";
  };
  rait = {
    pname = "rait";
    version = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6Y0s5/HUmWrZA6QmV5wYjB1M0Ab/jHM3TSruRpMRwtA=";
    };
    date = "2022-10-07";
  };
}
