# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  ariang = {
    pname = "ariang";
    version = "4ed53e27f5df3b6971c70075bc2f9c7492249b1e";
    src = fetchgit {
      url = "https://github.com/KireinaHoro/AriaNg";
      rev = "4ed53e27f5df3b6971c70075bc2f9c7492249b1e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-0IAe4/zmL9z/6Fm5Fw183RFVknHUnzz0i9w0uQ1sh0k=";
    };
  };
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "d528d8f934dd39f924461ab976f06d4ab7676f96";
    src = fetchgit {
      url = "https://github.com/felixonmars/dnsmasq-china-list";
      rev = "d528d8f934dd39f924461ab976f06d4ab7676f96";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PbrRtRi7gUQr/Q9chrWzkvuh79vqZ9w9tht/0WUZZ18=";
    };
  };
  hosts-blocklists = {
    pname = "hosts-blocklists";
    version = "653621fbc86ffae495fb80c0f769821def1a033f";
    src = fetchgit {
      url = "https://github.com/notracking/hosts-blocklists";
      rev = "653621fbc86ffae495fb80c0f769821def1a033f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-AL56q8Iho/eHIRLf8Hr+D7Ax9YfhztURPuVvOvnFWhU=";
    };
  };
  rait = {
    pname = "rait";
    version = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6Y0s5/HUmWrZA6QmV5wYjB1M0Ab/jHM3TSruRpMRwtA=";
    };
  };
}
