# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "aacfedad744977006e6a3cbc01195432b798ef68";
    src = fetchgit {
      url = "https://github.com/felixonmars/dnsmasq-china-list";
      rev = "aacfedad744977006e6a3cbc01195432b798ef68";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-EO/9JCGqCYjDBCVH/8EgcTPEwrZPib+s5IYnwY82TyM=";
    };
    date = "2025-10-04";
  };
  hosts-blocklists = {
    pname = "hosts-blocklists";
    version = "2ab426e806985d0d3d1c3eb447d7e772a836e10d";
    src = fetchgit {
      url = "https://github.com/notracking/hosts-blocklists";
      rev = "2ab426e806985d0d3d1c3eb447d7e772a836e10d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-nKNz9ux1FPxoL14VZtH/1tfnn67LeXmdVQJz7I9+Srk=";
    };
    date = "2023-06-26";
  };
  rait = {
    pname = "rait";
    version = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6Y0s5/HUmWrZA6QmV5wYjB1M0Ab/jHM3TSruRpMRwtA=";
    };
    date = "2022-10-07";
  };
  swan-updown = {
    pname = "swan-updown";
    version = "b16d2459003c19d93b0adf3a918207c22d0d7d4f";
    src = fetchgit {
      url = "https://github.com/6-6-6/swan-updown";
      rev = "b16d2459003c19d93b0adf3a918207c22d0d7d4f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Tb3YLgPXzH14W25z9t+KHWEgVMclUMQRqKcyqKMldhE=";
    };
    date = "2024-11-08";
  };
  vim-haskell-indent = {
    pname = "vim-haskell-indent";
    version = "67d33a27c3f31f0a31980e532abd6c0dda4d238d";
    src = fetchgit {
      url = "https://github.com/itchyny/vim-haskell-indent";
      rev = "67d33a27c3f31f0a31980e532abd6c0dda4d238d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DMQRtuEm/L6WWDhdfCJAfik4BzUCb00rGBw+m06w9C0=";
    };
    date = "2025-04-15";
  };
  vim-ripgrep = {
    pname = "vim-ripgrep";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "jremmen";
      repo = "vim-ripgrep";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-OvQPTEiXOHI0uz0+6AVTxyJ/TUMg6kd3BYTAbnCI7W8=";
    };
  };
}
