# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "16e4ab4c454898d396e405de6c888207571734c9";
    src = fetchgit {
      url = "https://github.com/felixonmars/dnsmasq-china-list";
      rev = "16e4ab4c454898d396e405de6c888207571734c9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-1noSir2jDU4f6KLwz9jKTaf1jQfODF6cVJepejPOFhY=";
    };
    date = "2024-10-27";
  };
  hosts-blocklists = {
    pname = "hosts-blocklists";
    version = "2ab426e806985d0d3d1c3eb447d7e772a836e10d";
    src = fetchgit {
      url = "https://github.com/notracking/hosts-blocklists";
      rev = "2ab426e806985d0d3d1c3eb447d7e772a836e10d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-nKNz9ux1FPxoL14VZtH/1tfnn67LeXmdVQJz7I9+Srk=";
    };
    date = "2023-06-26";
  };
  rait = {
    pname = "rait";
    version = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6Y0s5/HUmWrZA6QmV5wYjB1M0Ab/jHM3TSruRpMRwtA=";
    };
    date = "2022-10-07";
  };
  swan-updown = {
    pname = "swan-updown";
    version = "bc9851409c8b479e6546722ec6448f27a692be78";
    src = fetchgit {
      url = "https://github.com/6-6-6/swan-updown";
      rev = "bc9851409c8b479e6546722ec6448f27a692be78";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-MtM+3rzsTXqoR6Qa1BbZQD24X/4ZG1j40gG66gne8Xg=";
    };
    date = "2024-10-27";
  };
  vim-haskell-indent = {
    pname = "vim-haskell-indent";
    version = "bf6a26579b3296ac93f05d073625b54f09a4eddf";
    src = fetchgit {
      url = "https://github.com/itchyny/vim-haskell-indent";
      rev = "bf6a26579b3296ac93f05d073625b54f09a4eddf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Fqp6BRwfIWrS/ZC2Fg/h8V4y2VSV1sT8klajHwO2qis=";
    };
    date = "2024-10-27";
  };
  vim-ripgrep = {
    pname = "vim-ripgrep";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "jremmen";
      repo = "vim-ripgrep";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-OvQPTEiXOHI0uz0+6AVTxyJ/TUMg6kd3BYTAbnCI7W8=";
    };
  };
}
