on:
  repository_dispatch:
    types: [bump_dep]

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Bump dependency
    env:
      IMAGE_NAME: kireinahoro/flakes-base:v1
      TARFILE: ~/image-cache/flakes-base.tar
    steps:
      - name: checkout local repo
        uses: actions/checkout@v4
      - name: create image cache dir
        run: mkdir -p ~/image-cache
      - id: image-cache
        name: try load image from cache
        uses: actions/cache@v4
        with:
          path: ~/image-cache
          key: ${{runner.os}}-flake-image
      - if: steps.image-cache.outputs.cache-hit != 'true'
        name: cache miss; store image
        run: |
          docker pull $IMAGE_NAME
          docker save -o $TARFILE $IMAGE_NAME
      - if: steps.image-cache.outputs.cache-hit == 'true'
        name: cache hit; restore image
        run: docker load -i $TARFILE
      - name: bump flake input lock
        uses: ./actions/bump
        with:
          input: ${{ github.event.client_payload.input }}
      - name: commit new lock
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Bump lock for ${{ github.event.client_payload.input }}" -a
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: trigger new deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          event-type: deploy_flakes
