on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [deploy_flakes]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy flakes
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/image-cache
        with:
          image-name: kireinahoro/flakes-base:v1
      - name: deploy flake on kage
        uses: ./.github/actions/deploy
        with:
          flake: 'github:KireinaHoro/flakes'
          privkey: ${{ secrets.ACTIONS_PRIVKEY }}
          host: kage
      - name: deploy flake on shigeru
        uses: ./.github/actions/deploy
        with:
          flake: 'github:KireinaHoro/flakes'
          privkey: ${{ secrets.ACTIONS_PRIVKEY }}
          host: shigeru
