on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [deploy_flakes]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy flakes
    env:
      IMAGE_NAME: kireinahoro/flakes-base:v1
      TARFILE: ~/image-cache/flakes-base.tar
    steps:
      - name: checkout local action
        uses: actions/checkout@v4
      - name: create image cache dir
        run: mkdir -p ~/image-cache
      - id: image-cache
        name: try load image from cache
        uses: actions/cache@v4
        with:
          path: ~/image-cache
          key: ${{runner.os}}-flake-image
      - if: steps.image-cache.outputs.cache-hit != 'true'
        name: cache miss; store image
        run: |
          docker pull $IMAGE_NAME
          docker save -o $TARFILE $IMAGE_NAME
      - if: steps.image-cache.outputs.cache-hit == 'true'
        name: cache hit; restore image
        run: docker load -i $TARFILE
      - name: deploy flake on kage
        uses: ./actions/deploy
        with:
          flake: 'github:KireinaHoro/flakes'
          privkey: ${{ secrets.ACTIONS_PRIVKEY }}
          host: kage
