on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [deploy_flakes]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy flakes
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: hello
        with:
          flake: 'github:KireinaHoro/flakes'
          privkey: ${{ secrets.ACTIONS_PRIVKEY }}
